"""Add name, price, and description to Item

Revision ID: 06b2a9607342
Revises: 0fc97a09bc00
Create Date: 2025-07-05 01:46:01.478883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b2a9607342'
down_revision = '0fc97a09bc00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('name')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
